### ISSUE TITLE
Update winestreamproxy

### ISSUE THREAD

**Issue by InfinityGhost** [fufexan/nix-gaming#10]
The version of winestreamproxy provided by this flake constantly causes segfaults killing the entire wineserver.

**Comment by fufexan** [comment]
It stopped working a while ago, and the build system changed. Now I'm not really sure how to make it work properly. I've asked for help on the NixOS discord server but no one had an idea of how to fix it.

@LavaDesu told me we could go back to using [`wine-discord-ipc-bridge`](https://github.com/0e4ef622/wine-discord-ipc-bridge). I haven't tested it yet as I don't have much time, but could you test it? I noticed it stopped working on wine 6.15 and later, but it seems to have been updated since. If it works, we'll just replace `winestreamproxy` with `wdib`.

**Comment by fufexan** [comment]
Tried `wdib`, works flawlessly. As such, I've added it, and replaced occurences of `wsp` with it. Games should work properly now.

Still tried to update and build `wsp`. Although I'm getting closer, it's still broken so I marked it as such.
