### ISSUE TITLE
Problems using nix-gaming as a flake

### ISSUE THREAD

**Issue by makuru-dd** [fufexan/nix-gaming#79]
it is extremely confusing how you want me to install it
as a flake
       error: attribute 'inputs' missing

in nix stable way
error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument

**Comment by fufexan** [comment]
You seem to be using flakes, otherwise you wouldn't get the error about `sha256`.

If you're using flakes, I assume you're familiar with how you can add an input to your system configuration flake. This is no different. You add an input named `nix-gaming` with the url `github:fufexan/nix-gaming`.
After that, make sure you have `specialInputs = {inherit inputs;};` in your `nixpkgs.lib.nixosSystem` call, where you define your nixos configuration. Alternatively, make sure you have `extraSpecialInputs = {inherit inputs;};` in your `home-manager.lib.homeManagerConfiguration` call where you define your homeConfiguration.

The readme briefly mentions the instructions, since they are general in the flake world, so I should not need to repeat them here. Feel free to refer https://nixos.wiki/wiki/Flakes#Using_nix_flakes_with_NixOS.
